package com.abhijit.gamesolution;

import android.content.ClipData;import android.content.ClipboardManager;import android.content.Context;import android.content.Intent;import android.content.pm.ApplicationInfo;import android.content.pm.PackageInfo;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.Build;import android.view.Gravity;import android.view.MotionEvent;import android.view.View;import android.view.WindowManager;import android.widget.LinearLayout;import android.widget.ScrollView;import android.widget.TextView;import android.widget.Toast;import java.io.File;import java.io.IOException;import java.text.DateFormat;import java.util.Date;

public final class AppDetailInfoDialog {
 private static final int BG=Color.rgb(16,21,34),CARD=Color.rgb(28,35,52),WHITE=Color.WHITE,MUTED=Color.rgb(165,174,194),PRIMARY=Color.rgb(105,145,255);private static View currentDialog;private static WindowManager currentWindowManager;
 private AppDetailInfoDialog(){}
 public static boolean isShowing(){return currentDialog!=null;}
 public static void dismiss(){if(currentDialog==null)return;View v=currentDialog;WindowManager wm=currentWindowManager;currentDialog=null;currentWindowManager=null;if(wm!=null)try{wm.removeView(v);}catch(Exception ignored){}}
 public static void show(Context c,String pkg,WindowManager wm,View current,Runnable dismissMenu){
  dismiss();if(current!=null&&dismissMenu!=null)dismissMenu.run();PackageManager pm=c.getPackageManager();PackageInfo pi;
  try{pi=pm.getPackageInfo(pkg,PackageManager.GET_PERMISSIONS|PackageManager.GET_ACTIVITIES|PackageManager.GET_SERVICES|PackageManager.GET_RECEIVERS|PackageManager.GET_PROVIDERS);}catch(Exception e){Toast.makeText(c,"Unable to read app information: "+e.getClass().getSimpleName(),Toast.LENGTH_SHORT).show();return;}
  ApplicationInfo ai=pi.applicationInfo;if(ai==null){Toast.makeText(c,"Unable to read app information",Toast.LENGTH_SHORT).show();return;}
  try{
   LinearLayout root=new LinearLayout(c);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(c,18),dp(c,14),dp(c,18),dp(c,14));root.setBackground(round(c,BG,22));
   LinearLayout header=new LinearLayout(c);header.setGravity(Gravity.CENTER_VERTICAL);header.addView(text(c,"App Detail Info",20,WHITE,Typeface.BOLD),new LinearLayout.LayoutParams(0,-2,1));TextView close=text(c,"×",28,MUTED,Typeface.BOLD);close.setGravity(Gravity.CENTER);header.addView(close,new LinearLayout.LayoutParams(dp(c,42),dp(c,42)));root.addView(header);
   root.addView(text(c,safeLabel(pm,ai,pkg),17,WHITE,Typeface.BOLD),margin(c,-1,-2,0,2,0,0));LinearLayout packageRow=new LinearLayout(c);packageRow.setGravity(Gravity.CENTER_VERTICAL);TextView packageText=text(c,pkg,11,MUTED,Typeface.NORMAL);packageText.setSingleLine(true);packageText.setEllipsize(android.text.TextUtils.TruncateAt.MIDDLE);packageRow.addView(packageText,new LinearLayout.LayoutParams(0,-2,1));TextView copy=text(c,"▣",17,WHITE,Typeface.BOLD);copy.setGravity(Gravity.CENTER);packageRow.addView(copy,new LinearLayout.LayoutParams(dp(c,42),dp(c,38)));root.addView(packageRow,margin(c,-1,-2,0,0,0,10));
   copy.setOnClickListener(v->{ClipboardManager cb=(ClipboardManager)c.getSystemService(Context.CLIPBOARD_SERVICE);if(cb!=null){cb.setPrimaryClip(ClipData.newPlainText("Package name",pkg));Toast.makeText(c,"Package name copied",Toast.LENGTH_SHORT).show();}});
   ScrollView scroll=new ScrollView(c);LinearLayout content=new LinearLayout(c);content.setOrientation(LinearLayout.VERTICAL);addTwo(content,c,"Version",safeVersion(pi),"Version code",String.valueOf(versionCode(pi)));addTwo(content,c,"Target SDK",String.valueOf(ai.targetSdkVersion),"Min SDK",String.valueOf(minSdk(pi)));addTwo(content,c,"Activities",count(pi.activities),"Services",count(pi.services));addTwo(content,c,"Receivers",count(pi.receivers),"Providers",count(pi.providers));add(content,c,"UID",String.valueOf(ai.uid));addDate(content,c,"Installed",pi.firstInstallTime);addDate(content,c,"Last updated",pi.lastUpdateTime);add(content,c,"APK size",formatSize(sourceLength(ai)));add(content,c,"APK path",safePath(ai));add(content,c,"Status",(ai.enabled?"Enabled":"Disabled")+" • "+(((ai.flags&ApplicationInfo.FLAG_DEBUGGABLE)!=0)?"Debuggable":"Release")+" • "+(((ai.flags&ApplicationInfo.FLAG_SYSTEM)!=0)?"System app":"User app"));
   int pc=pi.requestedPermissions==null?0:pi.requestedPermissions.length;LinearLayout ps=section(c,"Permissions",pc);LinearLayout piw=new LinearLayout(c);piw.setOrientation(LinearLayout.VERTICAL);piw.setVisibility(View.GONE);if(pi.requestedPermissions!=null)for(String p:pi.requestedPermissions)item(piw,c,p);ps.addView(piw,new LinearLayout.LayoutParams(-1,-2));LinearLayout ph=(LinearLayout)ps.getChildAt(0);ph.setOnClickListener(v->toggle(ph,piw));content.addView(ps,margin(c,-1,-2,0,8,0,8));
   int cc=(pi.activities==null?0:pi.activities.length)+(pi.services==null?0:pi.services.length)+(pi.receivers==null?0:pi.receivers.length)+(pi.providers==null?0:pi.providers.length);LinearLayout cs=section(c,"Components",cc);LinearLayout ci=new LinearLayout(c);ci.setOrientation(LinearLayout.VERTICAL);ci.setVisibility(View.GONE);if(pi.activities!=null)for(android.content.pm.ActivityInfo x:pi.activities)item(ci,c,"Activity • "+x.name);if(pi.services!=null)for(android.content.pm.ServiceInfo x:pi.services)item(ci,c,"Service • "+x.name);if(pi.receivers!=null)for(android.content.pm.ActivityInfo x:pi.receivers)item(ci,c,"Receiver • "+x.name);if(pi.providers!=null)for(android.content.pm.ProviderInfo x:pi.providers)item(ci,c,"Provider • "+x.name);cs.addView(ci,new LinearLayout.LayoutParams(-1,-2));LinearLayout ch=(LinearLayout)cs.getChildAt(0);ch.setOnClickListener(v->toggle(ch,ci));content.addView(cs);
   scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout actions=new LinearLayout(c);actions.setOrientation(LinearLayout.HORIZONTAL);actions.setGravity(Gravity.CENTER_VERTICAL);TextView backup=button(c,"BACKUP (APK)",13);TextView share=button(c,"SHARE APP INFO",13);actions.addView(backup,new LinearLayout.LayoutParams(0,dp(c,50),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,dp(c,50),1);sp.setMargins(dp(c,8),0,0,0);actions.addView(share,sp);root.addView(actions,margin(c,-1,-2,0,10,0,0));backup.setOnClickListener(v->{dismiss();backupAndShare(c,ai,pkg);});share.setOnClickListener(v->{dismiss();share(c,buildShareText(pm,pi,ai,pkg));});
   WindowManager.LayoutParams lp=new WindowManager.LayoutParams(dp(c,350),dp(c,620),Build.VERSION.SDK_INT>=26?WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY:WindowManager.LayoutParams.TYPE_PHONE,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL|WindowManager.LayoutParams.FLAG_WATCH_OUTSIDE_TOUCH,android.graphics.PixelFormat.TRANSLUCENT);lp.gravity=Gravity.CENTER;root.setOnTouchListener((v,e)->{if(e.getActionMasked()==MotionEvent.ACTION_OUTSIDE){dismiss();return true;}return false;});close.setOnClickListener(v->dismiss());currentDialog=root;currentWindowManager=wm;wm.addView(root,lp);
  }catch(Exception e){currentDialog=null;currentWindowManager=null;Toast.makeText(c,"Unable to display: "+e.getClass().getSimpleName(),Toast.LENGTH_SHORT).show();}
 }
 private static String safeLabel(PackageManager pm,ApplicationInfo ai,String pkg){try{CharSequence s=pm.getApplicationLabel(ai);return s==null?pkg:s.toString();}catch(Exception e){return pkg;}}private static long sourceLength(ApplicationInfo ai){try{return ai.sourceDir==null?0:new File(ai.sourceDir).length();}catch(Exception e){return 0;}}private static String safePath(ApplicationInfo ai){return ai.sourceDir==null?"N/A":ai.sourceDir;}
 private static TextView button(Context c,String s,float z){TextView v=text(c,s,z,WHITE,Typeface.BOLD);v.setGravity(Gravity.CENTER);v.setMinHeight(dp(c,50));v.setBackground(round(c,PRIMARY,15));v.setPadding(dp(c,8),0,dp(c,8),0);v.setSingleLine(true);return v;}
 private static void backupAndShare(Context c,ApplicationInfo ai,String pkg){try{if(ai.sourceDir==null)throw new IOException("APK path unavailable");File src=new File(ai.sourceDir);if(!src.isFile()||!src.canRead())throw new IOException("APK unavailable or unreadable");File dir=new File(c.getCacheDir(),"shared_apk");if(!dir.exists()&&!dir.mkdirs()&&!dir.isDirectory())throw new IOException("Unable to create cache directory");File out=new File(dir,safeFileName(pkg)+".apk");try(java.io.InputStream in=new java.io.FileInputStream(src);java.io.OutputStream os=new java.io.FileOutputStream(out)){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)os.write(b,0,n);}if(!out.isFile()||out.length()==0)throw new IOException("APK backup was not created");Uri uri=ApkShareProvider.getUri(c,out);Intent i=new Intent(Intent.ACTION_SEND);i.setType("application/vnd.android.package-archive");i.putExtra(Intent.EXTRA_STREAM,uri);i.setClipData(ClipData.newRawUri("APK",uri));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_ACTIVITY_NEW_TASK);Intent chooser=Intent.createChooser(i,"Share APK");chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_GRANT_READ_URI_PERMISSION);c.startActivity(chooser);}catch(Exception e){Toast.makeText(c,"Unable to backup APK: "+e.getClass().getSimpleName()+" - "+String.valueOf(e.getMessage()),Toast.LENGTH_LONG).show();}}
 private static String safeFileName(String p){return p.replaceAll("[^a-zA-Z0-9._-]","_");}private static void addTwo(LinearLayout p,Context c,String k1,String v1,String k2,String v2){LinearLayout row=new LinearLayout(c);row.setOrientation(LinearLayout.HORIZONTAL);row.addView(card(c,k1,v1),weight(c,1,0));row.addView(card(c,k2,v2),weight(c,1,6));p.addView(row,margin(c,-1,-2,0,0,0,6));}private static LinearLayout.LayoutParams weight(Context c,float w,int left){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,w);p.setMargins(dp(c,left),0,0,0);return p;}private static LinearLayout card(Context c,String k,String v){LinearLayout x=new LinearLayout(c);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(c,12),dp(c,9),dp(c,8),dp(c,9));x.setBackground(round(c,CARD,12));x.addView(text(c,k,10,MUTED,Typeface.BOLD));x.addView(text(c,v,13,WHITE,Typeface.BOLD),margin(c,-1,-2,0,3,0,0));return x;}private static void add(LinearLayout p,Context c,String k,String v){p.addView(card(c,k,v),margin(c,-1,-2,0,0,0,6));}
 private static void addDate(LinearLayout p,Context c,String key,long time){LinearLayout x=card(c,key,formatTime(time));TextView ago=text(c,relativeAge(time),10,MUTED,Typeface.NORMAL);x.addView(ago,margin(c,-1,-2,0,2,0,0));p.addView(x,margin(c,-1,-2,0,0,0,6));}private static LinearLayout section(Context c,String title,int count){LinearLayout s=new LinearLayout(c);s.setOrientation(LinearLayout.VERTICAL);LinearLayout h=new LinearLayout(c);h.setGravity(Gravity.CENTER_VERTICAL);TextView t=text(c,title+" • "+count,13,WHITE,Typeface.BOLD);t.setGravity(Gravity.CENTER);h.addView(t,new LinearLayout.LayoutParams(0,-1,1));TextView a=text(c,"⌄",20,MUTED,Typeface.BOLD);a.setGravity(Gravity.CENTER);h.addView(a,new LinearLayout.LayoutParams(dp(c,42),-1));h.setPadding(dp(c,12),0,0,0);h.setBackground(round(c,CARD,14));s.addView(h,new LinearLayout.LayoutParams(-1,dp(c,48)));return s;}private static void toggle(LinearLayout header,LinearLayout content){TextView arrow=(TextView)header.getChildAt(1);boolean open=content.getVisibility()!=View.VISIBLE;content.setVisibility(open?View.VISIBLE:View.GONE);arrow.setText(open?"⌃":"⌄");}private static void item(LinearLayout p,Context c,String value){TextView v=text(c,"•  "+value,11,WHITE,Typeface.NORMAL);v.setPadding(dp(c,12),dp(c,7),dp(c,8),dp(c,7));v.setTextIsSelectable(true);p.addView(v);}private static TextView text(Context c,String s,float z,int col,int style){TextView v=new TextView(c);v.setText(s);v.setTextSize(z);v.setTextColor(col);v.setTypeface(Typeface.DEFAULT,style);return v;}private static GradientDrawable round(Context c,int col,int r){GradientDrawable d=new GradientDrawable();d.setColor(col);d.setCornerRadius(dp(c,r));return d;}private static LinearLayout.LayoutParams margin(Context c,int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(c,l),dp(c,t),dp(c,r),dp(c,b));return p;}private static int dp(Context c,int v){return(int)(v*c.getResources().getDisplayMetrics().density+.5f);}
 private static String count(Object[] a){return String.valueOf(a==null?0:a.length);}private static String safeVersion(PackageInfo p){return p.versionName==null?"Unknown":p.versionName;}private static long versionCode(PackageInfo p){return Build.VERSION.SDK_INT>=28?p.getLongVersionCode():p.versionCode;}private static int minSdk(PackageInfo p){return Build.VERSION.SDK_INT>=24?p.applicationInfo.minSdkVersion:0;}private static String formatTime(long t){return DateFormat.getDateTimeInstance(DateFormat.MEDIUM,DateFormat.SHORT).format(new Date(t));}private static String relativeAge(long t){long d=Math.max(0,(System.currentTimeMillis()-t)/(24L*60*60*1000));if(d==0)return"Today";if(d==1)return"1 day ago";return d+" days ago";}private static String formatSize(long b){if(b<1024)return b+" B";if(b<1024*1024)return String.format("%.1f KB",b/1024f);return String.format("%.1f MB",b/(1024f*1024f));}
 private static String buildShareText(PackageManager pm,PackageInfo pi,ApplicationInfo ai,String pkg){StringBuilder s=new StringBuilder("App Detail Info\n\n");s.append("Name: ").append(safeLabel(pm,ai,pkg)).append('\n').append("Package: ").append(pkg).append('\n').append("Version: ").append(safeVersion(pi)).append('\n').append("Version code: ").append(versionCode(pi)).append('\n').append("UID: ").append(ai.uid).append('\n').append("Target SDK: ").append(ai.targetSdkVersion).append('\n').append("Min SDK: ").append(minSdk(pi)).append('\n').append("Installed: ").append(formatTime(pi.firstInstallTime)).append(" ( ").append(relativeAge(pi.firstInstallTime)).append(" )\n").append("Last updated: ").append(formatTime(pi.lastUpdateTime)).append(" ( ").append(relativeAge(pi.lastUpdateTime)).append(" )\n").append("APK path: ").append(safePath(ai)).append('\n').append("APK size: ").append(formatSize(sourceLength(ai))).append('\n').append("Enabled: ").append(ai.enabled).append('\n').append("Debuggable: ").append((ai.flags&ApplicationInfo.FLAG_DEBUGGABLE)!=0).append('\n').append("System app: ").append((ai.flags&ApplicationInfo.FLAG_SYSTEM)!=0).append('\n');if(pi.requestedPermissions!=null){s.append("\nPermissions:\n");for(String p:pi.requestedPermissions)s.append("• ").append(p).append('\n');}return s.toString();}private static void share(Context c,String value){try{Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_SUBJECT,"App Detail Info");i.putExtra(Intent.EXTRA_TEXT,value);i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);Intent chooser=Intent.createChooser(i,"Share app information");chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);c.startActivity(chooser);}catch(Exception e){Toast.makeText(c,"Unable to share: "+e.getClass().getSimpleName()+" - "+String.valueOf(e.getMessage()),Toast.LENGTH_LONG).show();}}
}